version: "3"

vars:
    NAME: aii
    OUT: bin/{{.NAME}}
    CONFIG: config.json
    GOBUILD: go build -buildvcs=false -trimpath -ldflags="-s -w"
    WSL_DOCKER_BUILD: wsl docker build --progress plain -t cnk3x/{{.NAME}}:latest --platform linux/amd64,linux/arm64 .

tasks:
    default:
        cmds: [task: build]

    build:
        cmds:
            - GOOS=linux GOARCH=amd64 {{.GOBUILD}} -o {{.OUT}}-linux-amd64 ./
            - GOOS=linux GOARCH=arm64 {{.GOBUILD}} -o {{.OUT}}-linux-arm64 ./
            - GOOS=windows GOARCH=arm64 {{.GOBUILD}} -o {{.OUT}}.exe ./

    docker_build:
        deps:
            - build
        cmds:
            - "{{ .WSL_DOCKER_BUILD }} --load"

    docker_push:
        deps:
            - build
        cmds:
            - "{{ .WSL_DOCKER_BUILD }} --push"
