version: "3"

vars:
  WSL_DOCKER_BUILD: wsl docker build --progress plain -t cnk3x/aii:latest --platform linux/amd64,linux/arm64 .

tasks:
  default: { cmds: [task: build] }
  build: { cmds: ["{{ .WSL_DOCKER_BUILD }} --load"] }
  push: { cmds: ["{{ .WSL_DOCKER_BUILD }} --push"] }
  local: { cmds: ['go build -buildvcs=false -trimpath -ldflags="-s -w" ./'] }
